name: Deploy Flask Welcome App

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create tag
        id: vars
        run: |
          TAG=$(TZ=Asia/Jakarta date +"%m%d%y-%H%M%S")
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Generated tag: $TAG"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/temporary:welcome-app-${{ env.TAG }}
      - name: SSH key setup for VM
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.VM_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and deploy to VM
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/welcome-app:${{ env.TAG }}
            #docker stop welcome-app-1 || true
            #docker rm welcome-app-1 || true
            docker run -d --name welcome-app-1 -p 8000:5000 ${{ secrets.DOCKER_USERNAME }}/temporary:welcome-app-${{ env.TAG }}
          EOF
