name: Deploy Flask Welcome App

on:
  push:
    branches:
      - main

jobs:
  setup_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  creating_tag:
    runs-on: ubuntu-latest
    needs: setup_docker
    steps:
      - name: Create tag
        id: vars
        run: |
          TAG=$(TZ=Asia/Jakarta date +"%m%d%y-%H%M%S")
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Generated tag: $TAG"

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: [setup_docker, creating_tag]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/temporary:welcome-app-${{ needs.creating_tag.outputs.TAG }}
